---
title: "start here"
author: "Jen Richmond"
date: "21/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lets start at the very beginning…

# Abstract
Lots of researchers who are interested in open science, replication, and reproducibility use R. But how did they learn it? Research methods courses are most often not taught in R.  If you are not terribly familiar with coding in general, teaching yourself how to code in R is a big task, and doing it by yourself is lonely and frustrating. 

If you have been thinking of trying R but been scared of "writing code", this session is for you. Join folks from R-Ladies and start your journey towards reproducible analysis. You will learn how to find your way around RStudio, get your OWN data into R, clean it up a little, and generate some summary stats and plots. 

# By the end of the workshop you will be able to... 

1. Find your way around RStudio 
1. Set up an R project and understand how to use the `here` package to avoid filepath drama
1. Read your datafile into R, using functions from the `readr` and `datapasta` packages
1. Learn how to clean with the `janitor` package 
1. Convert your data from wide to long format and back again using functions from `tidyr`
1. Get summary statistics using functions from `skimr` and `dplyr` 
1. Plot your data using `ggplot` 

But perhaps most importantly, we will show you how to find solutions to your R problems on the internet and how to recognise when your google search has found a solution. 

# This workshop will be a good fit for you if… 
- you’ve been to an R training and it all made sense at the time, but when you got back to your lab you couldn’t get R to read your data. 
- you’ve tried to learn R by yourself and quickly got overwhelmed 
- you’ve wanted to try R but not been sure where to start
- you are a bit scared of “writing code”

# Things we will cover..

## Before we deal with data..
- we need to find our way around Rstudio (maybe customise how it looks?)
- set global settings so R doesn't remember
- make a new project 
- learn about here()
- learn about packages, how to install, how to call library()


## an aside about data structure

- human readable
- wide
- long
- hybrid


## Common things you deal when you first get data

- reading it in (csv, but maybe also from spss via haven)
- clean names (janitor)
- renaming things (dplyr)
- merge cells (?)
- empty rows (janitor)
- wide data long (tidyr)
- changing data types, making things factors
- maybe visualising/dealing with missing data? (naniar?)

## Get some summary stats
ym
- summary() skimr()
- filter()
- group_by() + summarise()


## Visualise
